# Generated by Django 2.2.5 on 2019-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(default=2, upload_to='recognet-processed-images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='processed_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='unprocessed_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='unprocessed_video_url',
            field=models.URLField(blank=True),
        ),
    ]
