# Generated by Django 2.2.5 on 2019-09-28 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_api', '0003_auto_20190928_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
