# Generated by Django 2.2.5 on 2019-09-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_api', '0004_auto_20190928_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
