# Generated by Django 2.2.5 on 2019-09-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_api', '0006_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
