# Generated by Django 2.2.5 on 2019-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition_api', '0007_auto_20190928_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='year_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'female')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
